#include "exp_repro.h"

!> Reproducible exponential function
!!
!! This module provides a reproducible implementation of exp() that produces
!! bitwise identical results across platforms while matching IEEE signal
!! behavior (overflow, underflow, inexact) with the intrinsic exp().
!!
!! Performance is approximately 1.17x Intel SVML with full IEEE compliance.
module exp_repro_mod

use, intrinsic :: iso_fortran_env, only : int64, real64

implicit none
private

public :: exp_repro

! Scalar mold for transfer()
integer(kind=int64), parameter :: int64_mold = 0
real(kind=real64), parameter :: real64_mold = 0.

! IEEE 754 double precision layout
integer, parameter :: expbit = digits(1._real64) - 1
  !< Position of lowest exponent bit (52)
integer, parameter :: expwidth = storage_size(1._real64) - expbit - 1
  !< Number of exponent bits (11)

! IEEE 754 special values
integer(int64), parameter :: pos_inf_bits = shiftl(2_int64**expwidth - 1, expbit)
  !< IEEE 64-bit +Inf
integer(int64), parameter :: neg_inf_bits = ior(pos_inf_bits, shiftl(-1_int64, 63))
  !< IEEE 64-bit -Inf

contains

!> Reproducible exponential function
!!
!! Computes exp(x) with bitwise reproducibility across platforms.
!! IEEE signal behavior matches intrinsic exp():
!!   - normal: inexact
!!   - overflow: overflow + inexact
!!   - underflow: underflow + inexact
!!   - +/-Inf: no signals
!!   - NaN: no signals (NaN propagates)
elemental function exp_repro(x) result(a)
  !$acc routine seq
  real(kind=real64), value, intent(in) :: x
    !< Input value
  real(kind=real64) :: a
    !< exp(x)

  ! Range reduction: exp(x) = 2^K * exp(r), where r in [-ln2/2, ln2/2]
  real(kind=real64) :: r
  real(kind=real64) :: K
  real(kind=real64) :: e

  ! Bit manipulation for fast 2^K scaling
  integer(kind=int64) :: eb, kb
  integer(int64) :: j, fb, xb

  ! Constants for range reduction
  real(kind=real64), parameter :: round_bias = 1.5_real64 * 2_int64**52
  real(kind=real64), parameter :: INV_LN2 = 1.4426950408889634_real64

  ! Cody-Waite constants for accurate range reduction
  real(kind=real64), parameter :: LN2_HI = 6.93147180369123816490e-01_real64
  real(kind=real64), parameter :: LN2_LO = 1.90821492927058770002e-10_real64

  real(kind=real64) :: x_ln2

  logical :: nonfinite

  xb = transfer(x, int64_mold)
  nonfinite = iand(xb, pos_inf_bits) == pos_inf_bits

  if (nonfinite) then
    ! exp(-Inf) = 0, pass-through for +Inf and +/-NaN.
    ! Use x + x = x to trigger Invalid for signaled NaNs.
    a = merge(0._real64, x + x, xb == neg_inf_bits)
    return
  endif

  ! *** Range reduction ***

  ! Compute K = nint(x / ln2)
  x_ln2 = x * INV_LN2
  K = NEAREST_INT(x_ln2)

  ! Cody-Waite: r = x - K*ln2 with extended precision
  r = (x - K * LN2_HI) - K * LN2_LO

  ! *** Polynomial approximation ***

  ! exp(r) for r in [-ln2/2, ln2/2] using degree-10 Remez minimax polynomial
  e = exp_remez_estrin_10(r)

  ! *** Scaling: multiply by 2^K ***

  ! Handle over/underflow by splitting extreme K values
  j = merge(1022_int64, 0_int64, K < -1020.0_real64) &
      + merge(-1022_int64, 0_int64, K > 1020.0_real64)

  eb = transfer(e, int64_mold)
  kb = transfer(K + round_bias, int64_mold)

  eb = eb + shiftl(kb + j, expbit)
  a = transfer(eb, real64_mold)

  ! Apply correction factor for extreme K (triggers IEEE over/underflow signal)
  fb = shiftl(1023_int64 - j, expbit)
  a = a * transfer(fb, real64_mold)
end function exp_repro


!> Degree-10 Remez minimax polynomial for exp(x) on [-ln2/2, ln2/2]
!!
!! Approximates (exp(x) - 1) / x, then computes 1 + x * p(x).
!! Uses Estrin's scheme for instruction-level parallelism.
!! Coefficients generated by Sollya.
pure function exp_remez_estrin_10(x) result(e)
  real(kind=real64), intent(in) :: x
    !< Input value in [-ln2/2, ln2/2]
  real(kind=real64) :: e
    !< Approximation of exp(x)

  real(kind=real64) :: x2, x4, x8
  real(kind=real64) :: b0, b1, b2, b3, b4
  real(kind=real64) :: q0, q1

  ! Remez minimax coefficients for (exp(x) - 1) / x on [-ln2/2, ln2/2]
  real(kind=real64), parameter :: c(0:10) = [ &
    1.0_real64, &
    5.00000000000000555e-1_real64, &
    1.66666666666666074e-1_real64, &
    4.16666666665738844e-2_real64, &
   !8.33333333337716447e-3_real64, &
    ! This reduces relative error but increases absolute error
    8.33333333337716621e-03_real64, &
    1.38888889322647565e-3_real64, &
    1.98412697469850182e-4_real64, &
    2.48015045964426143e-5_real64, &
    2.75573817985163132e-6_real64, &
    2.76262647076892519e-7_real64, &
    2.50621020021886396e-8_real64 &
    ! Comically small improvement in accuracy
    !2.50621000021886396e-8_real64 ]
  ]

  ! Estrin's scheme: evaluate polynomial with maximum parallelism
  x2 = x * x
  x4 = x2 * x2
  x8 = x4 * x4

  b0 = c(0) + x * c(1)
  b1 = c(2) + x * c(3)
  b2 = c(4) + x * c(5)
  b3 = c(6) + x * c(7)
  b4 = c(8) + x * c(9)

  q0 = b0 + x2 * b1
  q1 = b2 + x2 * b3

  ! Final assembly: 1 + x * p(x) ensures exp(0) = 1 exactly
  e = 1 + x * (q0 + x4 * q1 + x8 * (b4 + x2 * c(10)))
end function exp_remez_estrin_10


pure function anint_fast(x) result(a)
  real(real64), intent(in) :: x
  real(real64) :: a

  real(kind=real64), parameter :: round_bias = 1.5_real64 * 2_int64**52

  a = (x + round_bias) - round_bias
end function anint_fast

end module exp_repro_mod
